### ISSUE TITLE
Please provide a copyright Notice

### ISSUE THREAD

**Issue by ThaDafinser** [mimmi20/ua-comparator#1]
You copied some parts from UserAgentParser, which is no problem generally.

But it's require to leave at least a copyright notice.
http://choosealicense.com/licenses/mit/

Some parts i found
https://github.com/mimmi20/ua-comparator/search?utf8=%E2%9C%93&q=Could+not+get+valid&type=Code

![image](https://cloud.githubusercontent.com/assets/533017/14136601/eb06046e-f663-11e5-9bac-028a6e5d5745.png)

By side that, why you did not used that already available abstraction layer for this comparison instead of copy it?
Is there something missing for your case? In the raw result there is everything you need in it, if i not missed something.

//update/edit it's really no problem to use those parts, was just a bit shocked why you (sadly) copied it and could not reuse the abstraction layer, since the target is also to cover such comparisons

**Comment by mimmi20** [comment]
@ThaDafinser I have my own Abstraction layer, so I dont want to use yours. This library is only an comparator, so I dont want to use your parser. 

If I have implemented all features I think about, I want to compare memory usage and required time too. For this I had to split the code into parts. I also have implemented something like process isolation using the the internal PHP server for the local parsers.

**Comment by mimmi20** [comment]
There is a license file in the root directory of the project. Do you want a better notice in the classes?

**Comment by ThaDafinser** [comment]
E.g. in [this class](https://github.com/mimmi20/ua-comparator/blob/master/src/Module/Check/WhatIsMyBrowserCom.php) only minor things are different to the original source are different, so there should be at least a notice from which project/author this was taken original

Like mentioned in the MIT license of the original project
![image](https://cloud.githubusercontent.com/assets/533017/14140654/a72b69ac-f67a-11e5-8a36-c118bad38847.png)

**Comment by mimmi20** [comment]
I removed these classes
